daemon off;
#master_process off;
pid {PidFile};
worker_processes auto;
worker_rlimit_nofile {WorkerMaxOpenedFiles};
{NgnixUserLine}

events
{
	worker_connections 4096;
}

http
{
	server_tokens off;

	log_format upstreamlog '$remote_addr - $remote_user [$time_iso8601] '
						'    to: $upstream_addr $upstream_response_time ms '
						'    "$request" $status $body_bytes_sent $request_time ms '
						'    "$http_referer" "$http_user_agent"';

	map $http_upgrade $connection_upgrade
	{
		default upgrade;
		''	  close;
	}
{WebAppManagerUpstream}

	server
	{
		listen {BindTo}{Port} default_server;
		{DisableIPV6} listen [::]:{Port} default_server ipv6only=on;
		server_name _;
		return 444;
	}

	server
	{
		listen {BindTo}{Port};
		{DisableIPV6} listen [::]:{Port};
		server_name {DomainName} ~^[a-z0-9-]*\.{DomainNameEscaped}$ ;

		set $invalid_host "true";

		if ($host ~ "^{DomainNameEscaped}$" )
		{
			set $invalid_host "false";
		}

		if ($host ~ "^[a-z0-9-]*\.{DomainNameEscaped}$" )
		{
			set $invalid_host "false";
		}

		if ($invalid_host = "true")
		{
			return 444;
		}

{HTTPDefaultServerLocations}

		location /
		{
			add_header Set-Cookie "{HTTPRedirectReferrerCookie}=$http_referer; Secure; HttpOnly; Path=/; Domain=.{DomainName}";
			return 302 https://$host{SSLPortRewrite}$request_uri;
		}
	}

{WebAppManagerHTTPServers}

	ssl_certificate {Certificate}; # full path to SSL certificate and CA certificate concatenated together
	ssl_certificate_key {CertificateKey}; # full path to SSL key

	# performance enhancement for SSL
	#ssl_stapling on; # Not supported by nginx for BoringSSL
	ssl_session_cache shared:SSL:10m;
	ssl_session_timeout 5m;

	# safety enhancement to SSL: make sure we actually use a safe cipher
	ssl_prefer_server_ciphers on;
	ssl_protocols TLSv1.2;

	# Cipher list from: https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html
	ssl_ciphers 'AES256+AESGCM+EECDH:AES256+AESGCM+EDH:AES128+AESGCM+EECDH:AES128+AESGCM+EDH::AES256+EECDH+SHA384:AES256+EDH+SHA384:AES128+EECDH+SHA384:AES128+EDH+SHA384:AES256+EECDH+SHA256:AES256+EDH+SHA256:AES128+EECDH+SHA256:AES128+EDH+SHA256:AES256+EECDH:AES256+EDH:AES128+EECDH:AES128+EDH:!aNULL:!DSS:!SHA';
	ssl_ecdh_curve P-521:P-384;

	{ssl_dhparam}

	# config to enable HSTS(HTTP Strict Transport Security) https://developer.mozilla.org/en-US/docs/Security/HTTP_Strict_Transport_Security
	# to avoid ssl stripping https://en.wikipedia.org/wiki/SSL_stripping#SSL_stripping
{SecurityHeaders}

	server
	{
		listen {BindTo}{SSLPort} default_server ssl http2 backlog=1024;
		{DisableIPV6} listen [::]:{SSLPort} default_server ssl http2 ipv6only=on backlog=1024;
		ssl_reject_handshake on;
		server_name _;
		return 444;
	}

{WebAppManagerServers}

	types
	{
{ContentTypes}
	}
}
